package logic;

/**
 * Created by ahmedatef on 11/29/15.
 */
public enum Signal {
  SHAKEHAND_PACKET,
  REQUEST_PACKET_RETRANSMISSION,
  REQUEST_IMAGE,
  STARTING_IMAGE_TRANSMISSION,
  TRANSMISSION_COMPLETED,
  TRANSMISSION_COMPLETED_RECEIVED,
  PACKET_RECEIVED
}
